Algoritmo "Idade"
// Disciplina   : [PRSW]
// Professor    : Marcos
// Descrição   : verificar se é maior de idade
// Data atual  : 13/08/2024
Var
// Seção de Declarações das variáveis 
valor1 : Inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("a idade é: ")
leia(valor1)
se (valor1 > 18) entao
   escreva("com ", valor1, " anos é maior de idade")
senao
   escreva("com ", valor1, " anos não é maior de idade")
fimse

Fimalgoritmo